server {
    listen         80;
    server_name    _;
    resolver 127.0.0.11:53;

    location /api {
        include uwsgi_params;
        uwsgi_pass ${SERVER_NAME}:${SERVER_PORT};
    }

    location / {
        root   /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
